### ISSUE TITLE
Can't work with Django and DRF at the same time.

### ISSUE THREAD

**Issue by Abdullah0297445** [file-validator/file-validator#126]
**Describe the bug**
So, this library is very good, but there is a small issue with it. It only works if files are uploaded via admin site. It doesn't work well with DRF via POST request even when the correct parsers (MultipartParser) are set.

**To Reproduce**
1. Install Django=4.17 & DRF 3.14 to your project.
2. Create a simple model with FileField and FileValidator(part of this package) as the validator with the Filefield.
3. Make migrations, and migrate.
4. Go to admin site and try to upload any file.
5. Upload will work just fine.
6. Now try to create a CreateAPIView from DRF generics.
7. Add parser_classes = (MultiPartParser, ) to the view
8. Try to hit the POST endpoint with formdata containing a file.
9. AttributeError: '_io.BufferedRandom' object has no attribute 'size'

**Expected behavior**
File should be uploaded as it had been in case of the Admin site.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Docker Desktop v4.17.0
 - Django 4.17
 - DRF 3.14
 - file_validator 0.3.4

**Narrowed Issue**
 - Go to file_validator/models
 - Change line 178 to `current_file = value`
 - Now the DRF will start working and the Admin site upload will fail.
 - So either Django admin site file upload works or DRF file upload works at a time, but not both, together.

**Comment by Abdullah0297445** [comment]
**model.py**
```
from django.conf import settings
from django.db import models
from file_validator.models import FileValidator


class File(models.Model):
    file = models.FileField(
        validators=[
            FileValidator(
                libraries=["all"],
            acceptable_mimes=settings.ACCEPTABLE_FILE_TYPES,
            max_upload_file_size=settings.FILE_UPLOAD_MAX_MEMORY_SIZE,  # => 2.5 MB
            )
        ]
    )
```

**serializers.py**
```
class FileSerializer(serializers.ModelSerializer):
    class Meta:
        model = File
        fields = (
            'id',
            'file',
        )
        read_only = (
            'id',
        )
```

**view.py**
```
class UploadView(CreateAPIView):
    parser_classes = (MultiPartParser, )
    serializer_class = FileSerializer
```

**Comment by Abdullah0297445** [comment]
**Trace**
```
Traceback (most recent call last):
web                   |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
web                   |     response = get_response(request)
web                   |                ^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
web                   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web                   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
web                   |     return func(*args, **kwds)
web                   |            ^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
web                   |     return view_func(*args, **kwargs)
web                   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
web                   |     return self.dispatch(request, *args, **kwargs)
web                   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
web                   |     response = self.handle_exception(exc)
web                   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
web                   |     self.raise_uncaught_exception(exc)
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
web                   |     raise exc
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
web                   |     response = handler(request, *args, **kwargs)
web                   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 190, in post
web                   |     return self.create(request, *args, **kwargs)
web                   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 18, in create
web                   |     serializer.is_valid(raise_exception=True)
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
web                   |     self._validated_data = self.run_validation(self.initial_data)
web                   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 426, in run_validation
web                   |     value = self.to_internal_value(data)
web                   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 483, in to_internal_value
web                   |     validated_value = field.run_validation(primitive_value)
web                   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/fields.py", line 548, in run_validation
web                   |     self.run_validators(value)
web                   |   File "/usr/local/lib/python3.11/site-packages/rest_framework/fields.py", line 562, in run_validators
web                   |     validator(value)
web                   |   File "/usr/local/lib/python3.11/site-packages/file_validator/models.py", line 179, in __call__
web                   |     file_size = current_file.size
web                   |                 ^^^^^^^^^^^^^^^^^
web                   |   File "/usr/local/lib/python3.11/tempfile.py", line 478, in __getattr__
web                   |     a = getattr(file, name)
web                   |         ^^^^^^^^^^^^^^^^^^^
web                   | AttributeError: '_io.BufferedRandom' object has no attribute 'size'
```

**Comment by rzashakeri** [comment]
> **Describe the bug** So, this library is very good, but there is a small issue with it. It only works if files are uploaded via admin site. It doesn't work well with DRF via POST request even when the correct parsers (MultipartParser) are set.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install Django=4.17 & DRF 3.14 to your project.
> 
>     2. Create a simple model with FileField and FileValidator(part of this package) as the validator with the Filefield.
> 
>     3. Make migrations, and migrate.
> 
>     4. Go to admin site and try to upload any file.
> 
>     5. Upload will work just fine.
> 
>     6. Now try to create a CreateAPIView from DRF generics.
> 
>     7. Add parser_classes = (MultiPartParser, ) to the view
> 
>     8. Try to hit the POST endpoint with formdata containing a file.
> 
>     9. AttributeError: '_io.BufferedRandom' object has no attribute 'size'
> 
> 
> **Expected behavior** File should be uploaded as it had been in case of the Admin site.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Versions (please complete the following information):**
> 
>     * OS: Docker Desktop v4.17.0
> 
>     * Django 4.17
> 
>     * DRF 3.14
> 
>     * file_validator 0.3.4
> 
> 
> **Narrowed Issue**
> 
>     * Go to file_validator/models
> 
>     * Change line 178 to `current_file = value`
> 
>     * Now the DRF will start working and the Admin site upload will fail.
> 
>     * So either Django admin site file upload works or DRF file upload works at a time, but not both, together.

hi
this problem fixed in version 1.0.4 (#170 )
Now try it and see if this problem has been resolved for you too 
Just note that the new version is due to the overall change of the code structure you need to use DjangofileValidator instead of FileValidator

**Comment by rzashakeri** [comment]
> **Describe the bug** So, this library is very good, but there is a small issue with it. It only works if files are uploaded via admin site. It doesn't work well with DRF via POST request even when the correct parsers (MultipartParser) are set.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install Django=4.17 & DRF 3.14 to your project.
> 
>     2. Create a simple model with FileField and FileValidator(part of this package) as the validator with the Filefield.
> 
>     3. Make migrations, and migrate.
> 
>     4. Go to admin site and try to upload any file.
> 
>     5. Upload will work just fine.
> 
>     6. Now try to create a CreateAPIView from DRF generics.
> 
>     7. Add parser_classes = (MultiPartParser, ) to the view
> 
>     8. Try to hit the POST endpoint with formdata containing a file.
> 
>     9. AttributeError: '_io.BufferedRandom' object has no attribute 'size'
> 
> 
> **Expected behavior** File should be uploaded as it had been in case of the Admin site.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Versions (please complete the following information):**
> 
>     * OS: Docker Desktop v4.17.0
> 
>     * Django 4.17
> 
>     * DRF 3.14
> 
>     * file_validator 0.3.4
> 
> 
> **Narrowed Issue**
> 
>     * Go to file_validator/models
> 
>     * Change line 178 to `current_file = value`
> 
>     * Now the DRF will start working and the Admin site upload will fail.
> 
>     * So either Django admin site file upload works or DRF file upload works at a time, but not both, together.

Is fixed this problem ?

**Comment by Abdullah0297445** [comment]
Sorry man. Had a busy couple of days with work. Couldn't check the new version. Will do ASAP and let you know. Thanks for the fix : )
