### ISSUE TITLE
Is this a Django-only application? If not, Django dependency should be moved to optional dependencies.

### ISSUE THREAD

**Issue by barseghyanartur** [file-validator/file-validator#200]
**Is your feature request related to a problem? Please describe.**
ATM, Django is a required dependency. It's OK if this app is a Django-only.

**Describe the solution you'd like**
Only if this is a non-Django app or app that is used broader than Django-only, it's best to move the Django from required dependencies to optional dependencies.

Additionally, it would make sense to make it really clear in the documentation.

**Comment by rzashakeri** [comment]
> **Is your feature request related to a problem? Please describe.** ATM, Django is a required dependency. It's OK if this app is a Django-only.
> 
> **Describe the solution you'd like** Only if this is a non-Django app or app that is used broader than Django-only, it's best to move the Django from required dependencies to optional dependencies.
> 
> Additionally, it would make sense to make it really clear in the documentation.

Thank you for saying that I will try to fix it 🙏
Was really a good offer

**Comment by rzashakeri** [comment]
> **Is your feature request related to a problem? Please describe.** ATM, Django is a required dependency. It's OK if this app is a Django-only.
> 
> **Describe the solution you'd like** Only if this is a non-Django app or app that is used broader than Django-only, it's best to move the Django from required dependencies to optional dependencies.
> 
> Additionally, it would make sense to make it really clear in the documentation.

In version of 1.0.8 fixed problem [#201](https://github.com/file-validator/file-validator/pull/201)

you can install with 

`pip install file_validator[django]`

**Comment by rzashakeri** [comment]
> I think it's a little bit more complex than just that. The `utils` and `validator` modules both depend on the `exceptions` module, which in its turn import from Django. In my opinion, that it not well justified. Exceptions can do fine without and actually, whole Django dependent code better be moved to a separate module (`django_integration` or `django_file_validator`). Django better be tested all separately (in the CI/CD).

Thank you for your offer 🙏
I definitely think about it, and in the next version we might have had something to do with each
For now that all tests are successfully passed
