### ISSUE TITLE
Add settings for default libraries in Django

### ISSUE THREAD

**Issue by danilogbotelho** [file-validator/file-validator#248]
It would be awesome if instead of defining libraries in every model field, one could just set it project wide in settings.py

BTW, thanks for the great lib.

**Comment by rzashakeri** [comment]
> It would be awesome if instead of defining libraries in every model field, one could just set it project wide in settings.py
> 
> BTW, thanks for the great lib.

Hi 🖐
Thank you for good suggestions 
I will definitely add it in the new version and announce it below
