### ISSUE TITLE
Bad formatting of docstrings

### ISSUE THREAD

**Issue by DmytroLitvinov** [file-validator/file-validator#262]
**Describe the bug**
Here in commit applied bad formatting - https://github.com/file-validator/file-validator/commit/30a211158af2caf18bf72e5534f6f8a2641c67d5

**Comment by rzashakeri** [comment]
> **Describe the bug** Here in commit applied bad formatting - [30a2111](https://github.com/file-validator/file-validator/commit/30a211158af2caf18bf72e5534f6f8a2641c67d5)

Thanks for reporting 
I will fix it
