### ISSUE TITLE
Zip bomb validation

### ISSUE THREAD

**Issue by DmytroLitvinov** [file-validator/file-validator#263]
**Is your feature request related to a problem? Please describe.**
The problem is that we need to make more secure file upload according to [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html) and prevent zip bomb attacks in uploading.

**Describe the solution you'd like**
As a solution I see we can provide custom validator in the library to use it where we define maximum uncompressed size for example and verify zip file on it.

**Describe alternatives you've considered**
As a alternatives of course it can be written manually and reuse at project.

**Additional context**
We were on bug bounty and white hackers found problem on our project. More details about it posted in [blogpost "Django FileField validation and how we paid 550 CHF for that"](https://dmytrolitvinov.com/blog/django-filefield-validation/)

**Comment by rzashakeri** [comment]
> **Is your feature request related to a problem? Please describe.** The problem is that we need to make more secure file upload according to [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html) and prevent zip bomb attacks in uploading.
> 
> **Describe the solution you'd like** As a solution I see we can provide custom validator in the library to use it where we define maximum uncompressed size for example and verify zip file on it.
> 
> **Describe alternatives you've considered** As a alternatives of course it can be written manually and reuse at project.
> 
> **Additional context** We were on bug bounty and white hackers found problem on our project. More details about it posted in [blogpost "Django FileField validation and how we paid 550 CHF for that"](https://dmytrolitvinov.com/blog/django-filefield-validation/)

You mentioned a good point
I will definitely add it to the next versions
