### ISSUE TITLE
Bug with python-magic-bin==0.4.14

### ISSUE THREAD

**Issue by Abdullah0297445** [file-validator/file-validator#66]
**Describe the bug**
I am trying to install file_validator in my python-3.11 inside a docker container. I added file_validator==0.3 in my requirements.txt file. Ran pip install -r requirements.txt inside the container and ran into this error message:

ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from file-validator) (from versions: none)
#0 79.16 ERROR: No matching distribution found for python-magic-bin==0.4.14

**To Reproduce**
1. Create a dockerfile from python:3.11-slim as the base image
2. Install libmagic1 inside the container via: `RUN apt-get update -y && apt-get install libmagic1 libmagic-dev -y`
3. Add file_validator==0.3 to the requirements.txt
4. Rebuild the container so that newly added requirement is installed.
5. See error

**Expected behavior**
Requirements being installed without any issue.

**Screenshots**
<img width="805" alt="Screenshot 2023-02-28 at 8 26 05 PM" src="https://user-images.githubusercontent.com/34318082/221899150-e5e58c98-9fdd-424c-99fd-ce79e5ede2a8.png">

**Desktop (please complete the following information):**
 - OS: Docker Desktop (Mac OS Monterey 12.6.3)
 - Base Image: python:3.11-slim

**Additional context**
So, I do not know if this is the real issue, but found a workaround.
1. Fork this repo.
2. Comment out these lines of code in setup.py:

    ```PYTHON_MAGIC = "python-magic==0.4.27"
    PYTHON_MAGIC_BIN = "python-magic-bin==0.4.14"
    OS_NAME = platform.system()
    
    if OS_NAME == 'Windows':
        requirements.append(PYTHON_MAGIC_BIN)
    else:
        requirements.append(PYTHON_MAGIC)```

3. Append `"python-magic==0.4.27"` in the `requirements` list in setup.py
4. Voila! it works. It is very strange. Somehow the `if` condition is not being respected. As soon as i comment it out, it starts working. I ssh'ed into the docker container and checked the result of platform.system(). It was 'Linux'. So i have no clue why is `if` condition being evaluated as true.
5. This is my personal [fork](https://github.com/Abdullah0297445/file-validator) see the changes. These work for me.

**Comment by Abdullah0297445** [comment]
I just found out some very weird behaviour: 
1. If i simply fork the repo without making any change to it and use the forked github project for installation with pip via `pip install git+https://github.com/abdullah0297445/file-validator#egg=file-validator`. It doesn't give any errors at all.
3. If i simply use `pip install file_validator` it works fine but it installs the version 0.16 not 0.3.0 (latest)

I am starting to think the issue is with pip or somehow related to the build.

**Comment by rzashakeri** [comment]
> **Describe the bug** I am trying to install file_validator in my python-3.11 inside a docker container. I added file_validator==0.3 in my requirements.txt file. Ran pip install -r requirements.txt inside the container and ran into this error message:
> 
> ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from file-validator) (from versions: none) #0 79.16 ERROR: No matching distribution found for python-magic-bin==0.4.14
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Create a dockerfile from python:3.11-slim as the base image
> 
>     2. Install libmagic1 inside the container via: `RUN apt-get update -y && apt-get install libmagic1 libmagic-dev -y`
> 
>     3. Add file_validator==0.3 to the requirements.txt
> 
>     4. Rebuild the container so that newly added requirement is installed.
> 
>     5. See error
> 
> 
> **Expected behavior** Requirements being installed without any issue.
> 
> **Screenshots** <img alt="Screenshot 2023-02-28 at 8 26 05 PM" width="805" src="https://user-images.githubusercontent.com/34318082/221899150-e5e58c98-9fdd-424c-99fd-ce79e5ede2a8.png">
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Docker Desktop (Mac OS Monterey 12.6.3)
> 
>     * Base Image: python:3.11-slim
> 
> 
> **Additional context** So, I do not know if this is the real issue, but found a workaround.
> 
>     1. Fork this repo.
> 
>     2. Comment out these lines of code in setup.py:
>        ```
>        PYTHON_MAGIC_BIN = "python-magic-bin==0.4.14"
>        OS_NAME = platform.system()
>        
>        if OS_NAME == 'Windows':
>            requirements.append(PYTHON_MAGIC_BIN)
>        else:
>            requirements.append(PYTHON_MAGIC)```
>        ```
> 
>     3. Append `"python-magic==0.4.27"` in the `requirements` list in setup.py
> 
>     4. Voila! it works. It is very strange. Somehow the `if` condition is not being respected. As soon as i comment it out, it starts working. I ssh'ed into the docker container and checked the result of platform.system(). It was 'Linux'. So i have no clue why is `if` condition being evaluated as true.
> 
>     5. This is my personal [fork](https://github.com/Abdullah0297445/file-validator) see the changes. These work for me.

Hi thank you for reporting this problem 🙏
We need to check out why Platform.System () can't detect the operating system correctly.
This issue is open to solve it

> **Describe the bug** I am trying to install file_validator in my python-3.11 inside a docker container. I added file_validator==0.3 in my requirements.txt file. Ran pip install -r requirements.txt inside the container and ran into this error message:
> 
> ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from file-validator) (from versions: none) #0 79.16 ERROR: No matching distribution found for python-magic-bin==0.4.14
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Create a dockerfile from python:3.11-slim as the base image
> 
>     2. Install libmagic1 inside the container via: `RUN apt-get update -y && apt-get install libmagic1 libmagic-dev -y`
> 
>     3. Add file_validator==0.3 to the requirements.txt
> 
>     4. Rebuild the container so that newly added requirement is installed.
> 
>     5. See error
> 
> 
> **Expected behavior** Requirements being installed without any issue.
> 
> **Screenshots** <img alt="Screenshot 2023-02-28 at 8 26 05 PM" width="805" src="https://user-images.githubusercontent.com/34318082/221899150-e5e58c98-9fdd-424c-99fd-ce79e5ede2a8.png">
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Docker Desktop (Mac OS Monterey 12.6.3)
> 
>     * Base Image: python:3.11-slim
> 
> 
> **Additional context** So, I do not know if this is the real issue, but found a workaround.
> 
>     1. Fork this repo.
> 
>     2. Comment out these lines of code in setup.py:
>        ```
>        PYTHON_MAGIC_BIN = "python-magic-bin==0.4.14"
>        OS_NAME = platform.system()
>        
>        if OS_NAME == 'Windows':
>            requirements.append(PYTHON_MAGIC_BIN)
>        else:
>            requirements.append(PYTHON_MAGIC)```
>        ```
> 
>     3. Append `"python-magic==0.4.27"` in the `requirements` list in setup.py
> 
>     4. Voila! it works. It is very strange. Somehow the `if` condition is not being respected. As soon as i comment it out, it starts working. I ssh'ed into the docker container and checked the result of platform.system(). It was 'Linux'. So i have no clue why is `if` condition being evaluated as true.
> 
>     5. This is my personal [fork](https://github.com/Abdullah0297445/file-validator) see the changes. These work for me.

Hi thank you for reporting this problem 🙏
We need to check out why Platform.System () can't detect the operating system correctly.
This issue is open to solve it

**Comment by rzashakeri** [comment]
> I just found out some very weird behaviour:
> 
>     1. If i simply fork the repo without making any change to it and use the forked github project for installation with pip via `pip install git+https://github.com/abdullah0297445/file-validator#egg=file-validator`. It doesn't give any errors at all.
> 
>     2. If i simply use `pip install file_validator` it works fine but it installs the version 0.16 not 0.3.0 (latest)
> 
> 
> I am starting to think the issue is with pip or somehow related to the build.

![Screenshot 2023-03-01 170132](https://user-images.githubusercontent.com/62311769/222153325-ee0a84d7-280a-4bc2-bef5-b24de67769eb.png)

I think the problem is from your side or pip because for me the latest version is installed, but this is also the case again to make sure everything works right.

Thank you very much for reporting 🙏

**Comment by Abdullah0297445** [comment]
Yep it works now. : ) 🎉
Thanks for fixing it quickly

**Comment by rzashakeri** [comment]
> Yep it works now. : ) 🎉
> Thanks for fixing it quickly

Your Welcome 🙏💙
